CREATE TABLE "fronius"."current_data_meter" (
  "id"                                       SERIAL8,
  "current_ac_phase_1"                       DOUBLE PRECISION NOT NULL,
  "current_ac_phase_2"                       DOUBLE PRECISION,
  "current_ac_phase_3"                       DOUBLE PRECISION,
  "current_ac_sum"                           DOUBLE PRECISION NOT NULL,
  "enable"                                   BOOLEAN          NOT NULL DEFAULT FALSE,
  "energy_reactive_v_ar_ac_phase_1_consumed" INTEGER          NOT NULL,
  "energy_reactive_v_ar_ac_phase_1_produced" INTEGER          NOT NULL,
  "energy_reactive_v_ar_ac_phase_2_consumed" INTEGER,
  "energy_reactive_v_ar_ac_phase_2_produced" INTEGER,
  "energy_reactive_v_ar_ac_phase_3_consumed" INTEGER,
  "energy_reactive_v_ar_ac_phase_3_produced" INTEGER,
  "energy_reactive_v_ar_ac_sum_consumed"     INTEGER          NOT NULL,
  "energy_reactive_v_ar_ac_sum_produced"     INTEGER          NOT NULL,
  "energy_real_w_ac_minus_absolute"          INTEGER          NOT NULL,
  "energy_real_w_ac_phase_1_consumed"        INTEGER          NOT NULL,
  "energy_real_w_ac_phase_1_produced"        INTEGER          NOT NULL,
  "energy_real_w_ac_phase_2_consumed"        INTEGER,
  "energy_real_w_ac_phase_2_produced"        INTEGER,
  "energy_real_w_ac_phase_3_consumed"        INTEGER,
  "energy_real_w_ac_phase_3_produced"        INTEGER,
  "energy_real_w_ac_plus_absolute"           INTEGER          NOT NULL,
  "energy_real_w_ac_sum_consumed"            INTEGER          NOT NULL,
  "energy_real_w_ac_sum_produced"            INTEGER          NOT NULL,
  "frequency_phase_average"                  DOUBLE PRECISION NOT NULL,
  "meter_location_current"                   INTEGER          NOT NULL,
  "power_apparent_s_phase_1"                 DOUBLE PRECISION NOT NULL,
  "power_apparent_s_phase_2"                 DOUBLE PRECISION,
  "power_apparent_s_phase_3"                 DOUBLE PRECISION,
  "power_apparent_s_sum"                     DOUBLE PRECISION NOT NULL,
  "power_factor_phase_1"                     DOUBLE PRECISION NOT NULL,
  "power_factor_phase_2"                     DOUBLE PRECISION,
  "power_factor_phase_3"                     DOUBLE PRECISION,
  "power_factor_sum"                         DOUBLE PRECISION NOT NULL,
  "power_reactive_q_phase_1"                 DOUBLE PRECISION NOT NULL,
  "power_reactive_q_phase_2"                 DOUBLE PRECISION,
  "power_reactive_q_phase_3"                 DOUBLE PRECISION,
  "power_reactive_q_sum"                     DOUBLE PRECISION NOT NULL,
  "power_real_p_phase_1"                     DOUBLE PRECISION NOT NULL,
  "power_real_p_phase_2"                     DOUBLE PRECISION,
  "power_real_p_phase_3"                     DOUBLE PRECISION,
  "power_real_p_sum"                         DOUBLE PRECISION NOT NULL,
  "timestamp"                                TIMESTAMP        NOT NULL,
  "visible"                                  BOOLEAN          NOT NULL DEFAULT FALSE,
  "voltage_ac_phase_1"                       DOUBLE PRECISION NOT NULL,
  "voltage_ac_phase_2"                       DOUBLE PRECISION,
  "voltage_ac_phase_3"                       DOUBLE PRECISION,
  PRIMARY KEY ("id")
);

