package froniusController

type AutoGenerated struct {
	Body struct {
		Inverters struct {
			Num1 struct {
				DT     int `json:"DT"`
				EDay   int `json:"E_Day"`
				ETotal int `json:"E_Total"`
				EYear  int `json:"E_Year"`
				P      int `json:"P"`
			} `json:"1"`
		} `json:"Inverters"`
		Site struct {
			EDay               int         `json:"E_Day"`
			ETotal             int         `json:"E_Total"`
			EYear              int         `json:"E_Year"`
			MeterLocation      string      `json:"Meter_Location"`
			Mode               string      `json:"Mode"`
			PAkku              interface{} `json:"P_Akku"`
			PGrid              float64     `json:"P_Grid"`
			PLoad              float64     `json:"P_Load"`
			PPV                interface{} `json:"P_PV"`
			RelAutonomy        interface{} `json:"rel_Autonomy"`
			RelSelfConsumption interface{} `json:"rel_SelfConsumption"`
		} `json:"Site"`
		Version string `json:"Version"`
	} `json:"Body"`
	Head ResponseHeader `json:"Head"`
}
