// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-02-26 21:23:10.518645292 +0100 CET m=+0.066507078

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "title": "IoT API",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "basePath": "/1.0",
    "paths": {
        "/charger": {
            "get": {
                "description": "Get all chargers",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all chargers",
                "operationId": "charger-index",
                "responses": {
                    "200": {
                        "description": "Array of chargers",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        },
        "/charger/{id}": {
            "get": {
                "description": "Get one charger by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Get one charger by ID",
                "operationId": "get-charger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Charger ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Charger",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        },
        "/charger/{id}/ammeter_settings": {
            "get": {
                "description": "Get charger ammeter settings",
                "produces": [
                    "application/json"
                ],
                "summary": "Get charger ammeter settings",
                "operationId": "charger-get-ammeter-settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Charger ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ammeter Settings",
                        "schema": {
                            "type": "GetAmmeterSettingsResponse"
                        }
                    }
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
